// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Formula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SourceHench1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceHench2Id")
                        .HasColumnType("uuid");

                    b.Property<double>("SuccessRate")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TargetHenchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceHench1Id");

                    b.HasIndex("SourceHench2Id");

                    b.HasIndex("TargetHenchId");

                    b.ToTable("Formulas");
                });

            modelBuilder.Entity("Domain.Entities.Hench", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Henches");
                });

            modelBuilder.Entity("Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Domain.Entities.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("MapHenches", b =>
                {
                    b.Property<Guid>("MapsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HenchesId")
                        .HasColumnType("uuid");

                    b.HasKey("MapsId", "HenchesId");

                    b.HasIndex("HenchesId");

                    b.ToTable("MapHenches", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Formula", b =>
                {
                    b.HasOne("Domain.Entities.Hench", "SourceHench1")
                        .WithMany()
                        .HasForeignKey("SourceHench1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Hench", "SourceHench2")
                        .WithMany()
                        .HasForeignKey("SourceHench2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Hench", "TargetHench")
                        .WithMany()
                        .HasForeignKey("TargetHenchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceHench1");

                    b.Navigation("SourceHench2");

                    b.Navigation("TargetHench");
                });

            modelBuilder.Entity("MapHenches", b =>
                {
                    b.HasOne("Domain.Entities.Hench", null)
                        .WithMany()
                        .HasForeignKey("HenchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Map", null)
                        .WithMany()
                        .HasForeignKey("MapsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
