services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol/config.yml"]
    volumes:
      - ./monitoring/otel-collector/config.yml:/etc/otelcol/config.yml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"
    depends_on:
      - loki
      - tempo

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.55.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  loki:
    container_name: loki
    image: grafana/loki:3.2.0
    command: ["-config.file=/etc/loki/config.yml"]
    volumes:
      - ./monitoring/loki/config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki
    ports:
      - "3100:3100"

  tempo:
    container_name: tempo
    image: grafana/tempo:2.6.1
    command: ["-config.file=/etc/tempo/config.yml"]
    volumes:
      - ./monitoring/tempo/config.yml:/etc/tempo/config.yml:ro
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"

  grafana:
    container_name: grafana
    image: grafana/grafana:11.3.1
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo

  mix-formula-service:
    container_name: mix-formula-service
    image: mix-formula-service
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - otel-collector
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=mix-formula;Username=admin;Password=senha123"
      ASPNETCORE_URLS: http://+:8080
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: mix-formula-service
    ports:
      - "8080:8080"

volumes:
  prometheus-data:
  loki-data:
  tempo-data:
  grafana-data:

